acs: Sort ACS SKUs for readability
RedHatInsights/entitlements-config pull request #83
Opened 2024-02-05 19:43 UTC by rukletsov

2024-02-05 21:58 UTC, stehessel approved these changes

2024-02-06 00:21 UTC, stehessel requested changes
Actually can you do the same for https://github.com/RedHatInsights/entitlements-config/blob/master/configs/stage/bundles.yml to keep stage/prod consistent?

2024-02-06 21:38 UTC, stehessel approved these changes

2024-02-07 20:22 UTC, Ellen-Yi-Dong approved these changes
LGTM!

2024-02-07 20:22 UTC, merged